### ISSUE TITLE
Failed to initiate Questrade - __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by sabyasm** [tgardiner/questrade_api#1]
`Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from questrade_api import Questrade
>>> q = Questrade('WOSrhAAL1L1TysWNITnqUoAYIeDfEeV99')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
>>>
`

**Comment by tgardiner** [comment]
Thanks @sabyasm, I've corrected the readme to show the correct args, you should be able to init as follows:

```
from questrade_api import Questrade
q = Questrade(refresh_token='XXXXXXXXXXXXXX')
```

**Comment by sabyasm** [comment]
Thanks - worked fine. The project looks pretty neat. I hope you are expanding it to place orders as well?

**Comment by tgardiner** [comment]
@sabyasm that was my original plan, however I believe Questrade have removed the ability to place orders with the API. So I have no plans to add further functionality at this time
