### ISSUE TITLE
Questrade API Error Codes

### ISSUE THREAD

**Issue by MikeCas** [tgardiner/questrade_api#12]
Hello,
I often get the RemoteDisconnected error from the API (traceback after the message), but how can I get the Questrade API Error Codes that they have listed in their documentation? 

[https://www.questrade.com/api/documentation/rate-limiting](url)
[https://www.questrade.com/api/documentation/error-handling](url)

I am especially interested to know if I am getting their error 429 'Rate limit exceeded'. Not sure how to capture that from your library.

Thanks!
Mike

> ---------------------------------------------------------------------------
RemoteDisconnected                        Traceback (most recent call last)
<ipython-input-23-a9c3fd25e6e1> in <module>
      2 #q = Questrade(refresh_token='MkEKOubWvAyHugGYpE81nInoKB5RimNP0')
      3 q=Questrade()
----> 4 q.time
      5 #q.symbols_search(prefix='ARKF')['symbols'][0]['symbolId']
      6 #oids=",".join([str(x['symbolId']) for x in q.symbols(names='LMND,TSLA,AAPL')['symbols']])

~/opt/anaconda3/lib/python3.7/site-packages/questrade_api/questrade.py in time(self)
     79     @property
     80     def time(self):
---> 81         return self.__get(self.config['API']['time'])
     82 
     83     @property

~/opt/anaconda3/lib/python3.7/site-packages/questrade_api/questrade.py in __get(self, url, params)
     47         )
     48         try:
---> 49             r = urllib.request.urlopen(req)
     50             return json.loads(r.read().decode('utf-8'))
     51         except urllib.error.HTTPError as e:

~/opt/anaconda3/lib/python3.7/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

~/opt/anaconda3/lib/python3.7/urllib/request.py in open(self, fullurl, data, timeout)
    523             req = meth(req)
    524 
--> 525         response = self._open(req, data)
    526 
    527         # post-process response

~/opt/anaconda3/lib/python3.7/urllib/request.py in _open(self, req, data)
    541         protocol = req.type
    542         result = self._call_chain(self.handle_open, protocol, protocol +
--> 543                                   '_open', req)
    544         if result:
    545             return result

~/opt/anaconda3/lib/python3.7/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    501         for handler in handlers:
    502             func = getattr(handler, meth_name)
--> 503             result = func(*args)
    504             if result is not None:
    505                 return result

~/opt/anaconda3/lib/python3.7/urllib/request.py in https_open(self, req)
   1360         def https_open(self, req):
   1361             return self.do_open(http.client.HTTPSConnection, req,
-> 1362                 context=self._context, check_hostname=self._check_hostname)
   1363 
   1364         https_request = AbstractHTTPHandler.do_request_

~/opt/anaconda3/lib/python3.7/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1320             except OSError as err: # timeout error
   1321                 raise URLError(err)
-> 1322             r = h.getresponse()
   1323         except:
   1324             h.close()

~/opt/anaconda3/lib/python3.7/http/client.py in getresponse(self)
   1342         try:
   1343             try:
-> 1344                 response.begin()
   1345             except ConnectionError:
   1346                 self.close()

~/opt/anaconda3/lib/python3.7/http/client.py in begin(self)
    304         # read until we get a non-100 response
    305         while True:
--> 306             version, status, reason = self._read_status()
    307             if status != CONTINUE:
    308                 break

~/opt/anaconda3/lib/python3.7/http/client.py in _read_status(self)
    273             # Presumably, the server closed the connection before
    274             # sending a valid response.
--> 275             raise RemoteDisconnected("Remote end closed connection without"
    276                                      " response")
    277         try:

RemoteDisconnected: Remote end closed connection without response

**Comment by tgardiner** [comment]
The rate limit errors (http 429) and other general http errors should be returned to you by the library as they are caught here https://github.com/tgardiner/questrade_api/blob/master/questrade_api/questrade.py#L51.  In this case it's thrown a generic `URLError` which is not handled by this library.  Looks like the connection was closed with no response at all

If you craft a bad request, you should be able to see how those errors come back

**Comment by MikeCas** [comment]
Ok thank you. Your library is great - thank you for creating and maintaining it. However I have been underwhelmed with the Questrade API underneath the hood. Seems inconsistent and will decide to not return results just for fun. Regardless, this issue is closed.
