### ISSUE TITLE
Limited results from q.symbols_search(prefix='B'). It Returns only 20 objects

### ISSUE THREAD

**Issue by prubyholl** [tgardiner/questrade_api#4]
Please I am trying to run symbols search this way **q.symbols_search(prefix='B')** and it returns only 20 objects. Is there a way all results can be returned?

Thank you.

**Comment by tgardiner** [comment]
You can provide an offset to the symbols_search api endpoint like this:
`q.symbols_search(prefix='B', offset=20)` Which returns results 20-40 as expected.

Unfortunately the `offset` parameter combined with `prefix` seems to always return results, even if the symbol doesn't start with the supplied prefix.

You can test this by supplying a large offset to the `symbols_search` endpoint:

```
>>> for symbol in q.symbols_search(prefix='B', offset=5000)['symbols']:
...     print(symbol['symbol'])
...
GSP
HBCGF
HBD.TO
HBL.UN.TO
HBLK.TO
HBNNF
HBTPF
HBU.TO
HED.TO
HEU.TO
HFD.TO
HFU.TO
HGD.TO
HGU.TO
HIG.TO
HIU.TO
HIX.TO
HND.TO
HNU.TO
HNUZF
```

As you can tell none of the returned symbols are actually prefixed with **B**.

**Comment by tgardiner** [comment]
According to their documentation:

**Prefix:**  `Prefix of a symbol or any word in the description.`

So using `prefix='B'` will return any symbol that either starts with **B** or that has any word in its description starting with **B**.

I'm guessing that this is not the behaviour you are looking for, however you could loop over all of them using a generator like this:

```
def get_all_symbols(prefix):
    symbol_count = 0
    resp = q.symbols_search(prefix=prefix)
    while 'symbols' in resp and len(resp['symbols']) > 0:
        for symbol in resp['symbols']:
            symbol_count += 1
            yield symbol
        resp = q.symbols_search(prefix=prefix, offset=symbol_count)


for symbol in get_all_symbols('B'):
    print(symbol['symbol'])
```

**Comment by prubyholl** [comment]
Thank you very much. that works perfectly. and the function was exactly what I needed.
