### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by cr0n-dist0rti0n** [tgardiner/questrade_api#7]
*** Error Output Below ***

```
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
  obj, end = self.scan_once(s, idx)

builtins.StopIteration: 1

During handling of the above exception, another exception occurred:

￼ File "/dowload_questrade_data/questrade/questrade_play.py", line 4, in <module>
  q = Questrade(refresh_token='<my token code>')
File "/usr/local/lib/python3.7/site-packages/questrade_api/questrade.py", line 22, in __init__
  self.auth = Auth(**auth_kwargs, config=self.config)
File "/usr/local/lib/python3.7/site-packages/questrade_api/auth.py", line 20, in __init__
  self.__refresh_token(kwargs['refresh_token'])
File "/usr/local/lib/python3.7/site-packages/questrade_api/auth.py", line 39, in __refresh_token
  token = json.loads(r.read().decode('utf-8'))
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
  return _default_decoder.decode(s)
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
  raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

*** From 'decoder.py' ***

 ```
   def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.

        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.

        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
            raise JSONDecodeError("Expecting value", s, err.value) from None
        return obj, end

```
Issue with line 355: `raise JSONDecodeError("Expecting value", s, err.value) from None`

**Comment by MikeCas** [comment]
Hi there, everything was working fine for the last week, but I just started getting this error today after market close.
Tried reissuing tokens in my Questrade app but can't get connected again. Dead in the water.
Can you please help me ASAP, as I need to continue my coding before market open on Monday!! 
Thank you!!
Mike

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-2-be48af41044a> in <module>
      3 import socket
      4 import time
----> 5 q = Questrade(refresh_token='7jAw8xsOAZ3G4mi28ltsNBTcyn98yPkG0') 
      6 #q = Questrade()
      7 #Nv3g_DTtARaP4ByG5WjGloGyWKvPocFR0

C:\ProgramData\Anaconda3\lib\site-packages\questrade_api\questrade.py in __init__(self, **kwargs)
     20                        ['token_path', 'refresh_token']}
     21 
---> 22         self.auth = Auth(**auth_kwargs, config=self.config)
     23 
     24     def __read_config(self, fpath):

C:\ProgramData\Anaconda3\lib\site-packages\questrade_api\auth.py in __init__(self, **kwargs)
     18             self.token_path = TOKEN_PATH
     19         if 'refresh_token' in kwargs:
---> 20             self.__refresh_token(kwargs['refresh_token'])
     21 
     22     def __read_token(self):

C:\ProgramData\Anaconda3\lib\site-packages\questrade_api\auth.py in __refresh_token(self, token)
     37         r = request.urlopen(self.config['Auth']['RefreshURL'].format(token))
     38         if r.getcode() == 200:
---> 39             token = json.loads(r.read().decode('utf-8'))
     40             token['expires_at'] = str(req_time + token['expires_in'])
     41             self.__write_token(token)

C:\ProgramData\Anaconda3\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    355             parse_int is None and parse_float is None and
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:
    359         cls = JSONDecoder

C:\ProgramData\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

C:\ProgramData\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 2 (char 1)

**Comment by MikeCas** [comment]
I had this same issue come up on a Friday evening. After panicking and resetting all of my Questrade tokens, apps, etc, nothing worked. Went to sleep defeated. Saturday morning, however, everything was working again like it had been for the prior week. Perhaps a Questrade API server issue, but definitely not this Python pkg. In case anyone else finds this error, just breathe and sleep on it. Try it again tomorrow and refresh your tokens if you need. 

Thanks to tgardiner for this pkg... it makes the API easier for a dummy like me!!
MC

**Comment by saskatchewancatch** [comment]
Never had exactly this happen.

I'd account the occasional hiccup that goes away with time to server maintenance. Their login page may be up online on questrade.com, but their API backends might be down. This happened yesterday. The API backend wasn't up until this morning.
